# Generated by Django 5.2.7 on 2025-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himuser',
            name='location',
            field=models.CharField(blank=True, choices=[('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Rishikesh', 'Rishikesh'), ('Nainital', 'Nainital'), ('Almora', 'Almora'), ('Mussoorie', 'Mussoorie'), ('Ranikhet', 'Ranikhet'), ('Kedarnath', 'Kedarnath'), ('Badrinath', 'Badrinath'), ('Gangotri', 'Gangotri'), ('Yamunotri', 'Yamunotri'), ('Pithoragarh', 'Pithoragarh'), ('Champawat', 'Champawat'), ('Tehri', 'Tehri'), ('Joshimath', 'Joshimath'), ('Kotdwar', 'Kotdwar'), ('Haldwani', 'Haldwani'), ('Roorkee', 'Roorkee')], max_length=255, null=True),
        ),
    ]
