# Generated by Django 5.2.7 on 2025-10-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='hazard',
            new_name='hazard_type',
        ),
    ]
